# Generated by Django 5.2.7 on 2025-11-21 17:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('garzon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_anterior', models.PositiveIntegerField(help_text='Precio anterior en pesos chilenos (entero positivo)', validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_nuevo', models.PositiveIntegerField(help_text='Precio nuevo en pesos chilenos (entero positivo)', validators=[django.core.validators.MinValueValidator(1)])),
                ('razon_cambio', models.TextField(blank=True, null=True)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_precios', to='garzon.producto')),
            ],
            options={
                'verbose_name': 'Historial de Precio',
                'verbose_name_plural': 'Historial de Precios',
                'db_table': 'historial_precio',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
