# Generated by Django 5.2.7 on 2025-11-05 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_habitacion', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('E', 'Enviada')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComandaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('ingredientes', models.TextField(blank=True, null=True)),
                ('imagen', models.CharField(blank=True, max_length=500, null=True)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='garzon.comanda')),
            ],
        ),
    ]
