# Generated by Django 5.2.7 on 2025-11-18 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garzon', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('E', 'Enviada'), ('L', 'Lista'), ('A', 'Anulada')], default='P', max_length=1),
        ),
    ]
