# Generated by Django 5.2.7 on 2025-11-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garzon', '0002_clienteexterno_comanda_cliente_externo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='numero_habitacion',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
